### PR TITLE
Add a short description of MEWarpX to the docs

### PR DESCRIPTION
**Pull request by roelof-groenewald**

### CODE REVIEW

**Comment by KZhu-ME** [comment]
Here's a link to the docs build for this PR: https://mewarpx--94.org.readthedocs.build/en/94/

**Review by KZhu-ME — CHANGES_REQUESTED** [review]
The intro looks good!
Now that we have a short description, do you think we should reformat the home page? I was thinking, instead of having the description on its own separate page, we should move it to the home page, and remove the current table of contents from the home page (since the table of contents is always visible on the left hand navigation column). We should also put the `Authors` section and a  link to the github repo on the home page as well.

**Review by peterscherpelz — APPROVED** [review]
Thanks! Looks good :)

**Review by KZhu-ME — APPROVED** [review]
Wow this looks so good!

**Pull request merged**
